import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence} from 'framer-motion';
import {Heart,Music2,Volume2,VolumeX,ChevronDown,Gift,Mail,Sparkles,Send,LockKeyhole,X} from 'lucide-react';
import './style.css';

const CONFIG={
 name:'Savira', senderName:'Aku', pin:'021128', birthdayDate:'02 November',
 whatsapp:'628123456789', music:'/music/our-song.mp3',
 photos:{cover:'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&q=85',letter1:'https://images.unsplash.com/photo-1520857014576-2c4f4c972b57?auto=format&fit=crop&w=1200&q=85',letter2:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',letter3:'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1200&q=85',letter4:'https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=1200&q=85',special:'https://images.unsplash.com/photo-1494774157365-9e04c6720e47?auto=format&fit=crop&w=1200&q=85'},
 gifs:{birthday:'https://media.giphy.com/media/g9582DNuQppxC/giphy.gif',love:'https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif',flower:'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif'}
};
const letters=[
 ['Tentang Kamu','Ada banyak hal kecil tentang kamu yang entah kenapa selalu berhasil tinggal lebih lama di pikiranku. Senyummu, caramu bercerita, bahkan hal-hal sederhana yang mungkin tidak kamu sadari. Aku suka mengenalmu pelan-pelan, tanpa perlu memaksa cerita menjadi apa pun.',CONFIG.photos.letter1],
 ['Hal-Hal Kecil Yang Aku Suka','Aku suka ketika kamu menjadi dirimu sendiri. Cara kamu tertawa, cara kamu merespons sesuatu, dan perhatian kecil yang mungkin menurutmu biasa saja. Buatku, hal-hal sederhana itu justru yang paling mudah diingat.',CONFIG.photos.letter2],
 ['Yang Ingin Aku Katakan','Mungkin aku tidak selalu pandai mengatakan apa yang sebenarnya kurasakan. Tapi kalau ada satu hal yang ingin kamu tahu, kamu adalah seseorang yang berarti. Aku senang pernah punya kesempatan untuk mengenalmu lebih dekat.',CONFIG.photos.letter3],
 ['Satu Surat Paling Spesial','Hari ulang tahunmu membuatku punya alasan untuk menulis semua ini. Aku tidak tahu cerita kita akan berjalan ke mana, tapi aku ingin hari ini menyisakan satu kenangan kecil yang hangat untukmu. Semoga kamu selalu dikelilingi hal-hal baik.',CONFIG.photos.letter4],
 ['Surat Kelima — Tentang Senyummu','Ada senyum yang cuma berlangsung beberapa detik, tetapi bisa tinggal di kepala seharian. Senyummu termasuk salah satunya. Semoga kamu selalu punya banyak alasan untuk tersenyum.',CONFIG.photos.letter1],
 ['Surat Keenam — Kalau Kamu Lelah','Kalau suatu hari kamu merasa lelah, istirahatlah tanpa merasa bersalah. Kamu tidak harus selalu kuat. Semoga kamu dikelilingi orang-orang yang membuatmu merasa aman, dihargai, dan disayangi.',CONFIG.photos.letter2],
 ['Surat Ketujuh — Kejujuranku','Aku tidak ingin membuat semua ini terasa seperti kewajiban untuk menjawab. Aku hanya ingin jujur bahwa perasaanku kepadamu tulus. Apa pun jawabanmu, terima kasih sudah menjadi bagian dari cerita yang indah ini.',CONFIG.photos.letter3],
 ['Surat Kedelapan — Sampai Halaman Terakhir','Kalau kamu sudah sampai di surat terakhir, terima kasih. Semoga hadiah kecil ini menjadi kenangan yang hangat. Selamat ulang tahun, Savira. Semoga umur barumu membawa banyak cinta, keberanian, dan kebahagiaan.',CONFIG.photos.letter4]
];

function App(){
 const [stage,setStage]=useState('intro'),[pin,setPin]=useState(''),[music,setMusic]=useState(false),[letter,setLetter]=useState(null),[answer,setAnswer]=useState(null),[custom,setCustom]=useState(''),[surprise,setSurprise]=useState(false),[menu,setMenu]=useState(false);
 const audio=useRef(null); const pinRef=useRef(null);
 const particles=useMemo(()=>Array.from({length:34},(_,i)=>i),[]);
 useEffect(()=>{audio.current=new Audio(CONFIG.music);audio.current.loop=true;audio.current.volume=.38;return()=>audio.current?.pause()},[]);
 useEffect(()=>{const key=e=>{if(e.key==='Escape'){setLetter(null);setAnswer(null);setSurprise(false)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 useEffect(()=>{document.body.style.overflow=(letter!==null||answer||surprise)?'hidden':'';return()=>{document.body.style.overflow=''}},[letter,answer,surprise]);
 const startMusic=()=>{audio.current?.play().then(()=>setMusic(true)).catch(()=>setMusic(false))};
 const enter=()=>{if(pin===CONFIG.pin){startMusic();setStage('loading');setTimeout(()=>setStage('envelope'),5000)}};
 const whatsapp=msg=>window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener,noreferrer');
 const scrollTo=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})};
 return <div className="app"><div className="ambient"/>{particles.map(i=><span className="petal" key={i} style={{'--i':i}}/>)}
  <AnimatePresence mode="wait">
   {stage==='intro'&&<motion.section className="center-screen intro" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="moon">♡</div><p className="eyebrow">A LITTLE WORLD MADE FOR YOU</p><h1>Tonight, this little world<br/><em>belongs to you.</em></h1><p className="muted">Ada sesuatu yang aku siapkan khusus untukmu...</p><button className="primary" onClick={()=>{setStage('pin');setTimeout(()=>pinRef.current?.focus(),100)}}>Enter <Heart size={16}/></button></motion.section>}
   {stage==='pin'&&<motion.section className="center-screen" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} exit={{opacity:0}}><div className="icon-orb"><LockKeyhole/></div><p className="eyebrow">A LITTLE SECRET</p><h2>Masukkan tanggal yang mungkin sudah kamu tahu.</h2><div className="pinbox">{[0,1,2,3,4,5].map(i=><span key={i} className={pin[i]?'filled':''}>{pin[i]||'•'}</span>)}</div><input ref={pinRef} className="pin-input-visible" type="tel" inputMode="numeric" pattern="[0-9]*" maxLength={6} autoComplete="one-time-code" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} onKeyDown={e=>e.key==='Enter'&&enter()} placeholder="Ketik 6 digit PIN" aria-label="PIN"/><button className="primary" onClick={enter} disabled={pin.length!==6}>Buka hadiah <Sparkles size={16}/></button>{pin.length===6&&pin!==CONFIG.pin&&<p className="error">Hmm... PIN-nya belum tepat 🤭 Coba lagi.</p>}</motion.section>}
   {stage==='loading'&&<motion.section className="cinematic" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="flower-scene"><div className="flower flower-a">🌸</div><div className="flower flower-b">🌷</div><div className="ring">💍</div><div className="sparkle s1">✦</div><div className="sparkle s2">✧</div></div><p className="eyebrow">A LITTLE SURPRISE FOR YOU...</p><h1>Selamat Ulang Tahun</h1><h2>{CONFIG.name} <span>♡</span></h2><p>Semoga hari ini menjadi salah satu hari paling indah untukmu...</p><button className="ghost" onClick={()=>setStage('envelope')}>Skip ♡</button></motion.section>}
   {stage==='envelope'&&<motion.section className="center-screen" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0}}><div className="envelope-wrap" onClick={()=>setStage('main')}><div className="envelope"><div className="seal">♡</div><div className="flap"/><div className="letter-peek">For Someone Special</div></div></div><p className="eyebrow">A LETTER FOR YOU</p><h2>There is something I want you to read...</h2><button className="primary" onClick={()=>setStage('main')}>Open Me <Mail size={17}/></button></motion.section>}
  </AnimatePresence>
  {stage==='main'&&<>
   <header className="nav"><div className="brand">♡ {CONFIG.name}</div><nav className={menu?'open':''}><button onClick={()=>scrollTo('letters')}>Letters</button><button onClick={()=>scrollTo('memories')}>Memories</button><button onClick={()=>scrollTo('birthday')}>Birthday</button><button onClick={()=>scrollTo('surprise')}>Surprise 🎁</button></nav><div className="nav-actions"><button className="music" onClick={()=>{if(music){audio.current.pause();setMusic(false)}else startMusic()}}>{music?<Volume2 size={16}/>:<VolumeX size={16}/>}<Music2 size={15}/></button><button className="menu-toggle" onClick={()=>setMenu(v=>!v)} aria-label="Menu">☰</button></div></header>
   <main>
    <section className="hero section"><div className="hero-copy"><p className="eyebrow">02 NOVEMBER · A DAY FOR YOU</p><h1>Untuk <em>{CONFIG.name}</em>,<br/>yang selalu punya<br/>cara sendiri untuk<br/><span>membuat hari terasa indah.</span></h1><p className="lead">Hari ini bukan cuma tentang bertambahnya usia. Ini tentang merayakan seseorang yang keberadaannya berarti.</p><button className="primary" onClick={()=>scrollTo('letters')}>Buka semua surat <ChevronDown size={17}/></button></div><div className="hero-photo"><img src={CONFIG.photos.cover} alt={CONFIG.name}/><div className="photo-note">a little memory ♡</div></div></section>
    <section className="section intro-letter"><div className="paper"><p className="eyebrow">SURAT UTAMA</p><h2>Untuk kamu...</h2><img src={CONFIG.photos.cover} alt="Kenangan"/><div className="scroll-letter"><p>Kalau kamu sampai di halaman ini, berarti kamu sudah membuka sesuatu yang memang aku buat untukmu. Aku tidak ingin membuat hadiah yang hanya selesai ketika dibuka. Aku ingin setiap bagian kecilnya menyimpan satu pesan: bahwa hari ini kamu layak dirayakan.</p><p>Aku berharap kamu membaca semuanya dengan senyum. Tidak perlu terburu-buru. Anggap saja ini seperti aku duduk di dekatmu dan menceritakan hal-hal yang selama ini mungkin sulit aku ucapkan.</p><p className="signature">— {CONFIG.senderName} ♡</p></div></div></section>
    <section id="letters" className="section"><div className="section-head"><p className="eyebrow">LOVE LETTER COLLECTION</p><h2>Delapan surat, delapan cerita kecil.</h2></div><div className="letter-grid">{letters.map((l,i)=><motion.button whileHover={{y:-8,rotate:i%2?1:-1}} whileTap={{scale:.98}} className="letter-card" key={i} onClick={()=>setLetter(i)}><div className="mini-envelope"><span>♡</span></div><small>LETTER 0{i+1}</small><h3>{l[0]}</h3><p>Klik untuk membuka surat...</p></motion.button>)}</div></section>
    <section id="memories" className="section memories"><div className="section-head"><p className="eyebrow">LITTLE MOMENTS</p><h2>Beberapa hal yang ingin disimpan.</h2></div><div className="polaroids"><figure className="polaroid p1"><img src={CONFIG.photos.letter1} alt="Memory 1"/><figcaption>A moment I don't want to forget.</figcaption></figure><figure className="polaroid p2"><img src={CONFIG.photos.letter2} alt="Memory 2"/><figcaption>Your smile, quietly unforgettable.</figcaption></figure><figure className="polaroid p3"><img src={CONFIG.photos.letter3} alt="Memory 3"/><figcaption>One little memory ♡</figcaption></figure></div></section>
    <section className="section garden"><div className="garden-copy"><p className="eyebrow">FLOWERS FOR YOU</p><h2>Kalau setiap bunga punya pesan...</h2><p>biarkan mereka menyampaikannya satu per satu.</p></div><div className="flowers"><span>🌹</span><span>🌷</span><span>🌸</span><span>💐</span><span>🌺</span></div></section>
    <section className="section reasons"><p className="eyebrow">IF YOU EVER ASK WHY</p><h2>Hal-hal kecil yang aku suka tentang kamu.</h2><div className="reason-list">{['Senyummu yang datang tanpa banyak usaha.','Cara kamu menjadi dirimu sendiri.','Hal-hal kecil yang mungkin kamu anggap biasa.','Caramu membuat hari yang biasa terasa sedikit berbeda.','Karena kamu adalah kamu.'].map((x,i)=><div className="reason" key={x}><b>0{i+1}</b><span>{x}</span><Heart size={18}/></div>)}</div></section>
    <section id="birthday" className="section birthday"><div className="cake">🎂</div><p className="eyebrow">TODAY IS YOUR DAY</p><h1>Happy Birthday,<br/><em>{CONFIG.name} ♡</em></h1><p>Semoga umur yang baru membawa lebih banyak alasan untuk tersenyum, lebih banyak hal baik untuk dikenang, dan lebih banyak mimpi yang berhasil kamu capai.</p><div className="wish">“Semoga kamu selalu menemukan cahaya bahkan di hari yang paling sederhana.”</div></section>
    <section className="section special"><div className="special-card"><img src={CONFIG.photos.special} alt="Special"/><div><p className="eyebrow">A SPECIAL MESSAGE</p><h2>Ada satu hal yang ingin aku titipkan.</h2><p>Aku tidak tahu apakah semua kata di sini bisa menjelaskan apa yang sebenarnya ingin aku sampaikan. Tapi setidaknya, semoga kamu tahu bahwa membuat hadiah ini adalah caraku mengatakan: kamu spesial.</p><p>Dan apa pun yang terjadi setelah halaman terakhir nanti, aku tetap berharap ulang tahunmu dipenuhi kebahagiaan.</p></div></div></section>
    <section id="surprise" className="section surprise-section"><div className="section-head"><p className="eyebrow">ONE MORE THING</p><h2>Ada kado kecil untukmu 🎁</h2><p className="lead center">Buka pelan-pelan. Jangan kaget kalau isinya ramai. ♡</p></div><button className="gift-box" onClick={()=>setSurprise(true)}><span className="gift-emoji">🎁</span><span className="gift-glow"/><strong>OPEN SURPRISE</strong><small>klik kado ini</small></button></section>
    <section className="section final-letter"><div className="paper dark-paper"><div className="heartbeat">♡</div><p className="eyebrow">ONE LAST LETTER</p><h2>Kalau kamu mau membaca satu hal sampai selesai...</h2><div className="scroll-letter"><p>Aku ingin kamu tahu bahwa aku tidak membuat semua ini untuk memaksamu menjawab apa pun. Aku membuatnya karena ada seseorang yang ingin aku rayakan hari ini—kamu.</p><p>Mungkin aku terlalu banyak berharap, mungkin juga tidak. Tapi aku ingin jujur tentang satu hal: aku menyukaimu. Dan kalau ternyata perasaan ini punya tempat di hatimu juga, mungkin kita bisa mulai menulis cerita yang baru.</p><p className="signature">Selamat ulang tahun, {CONFIG.name}. ♡</p></div></div></section>
    <section className="section question"><p className="eyebrow">ONE LAST QUESTION</p><h1>{CONFIG.name}...</h1><p className="question-lead">Setelah semua surat kecil ini,<br/>aku ingin bertanya sesuatu.</p><h2>Mau nggak jadi pacar aku? <span>♡</span></h2><div className="answer-buttons"><button className="primary" onClick={()=>setAnswer('yes')}>💗 MAU</button><button className="soft" onClick={()=>setAnswer('no')}>🌸 GAK DULU</button><button className="outline" onClick={()=>setAnswer('custom')}>💌 JAWAB SESUAI HATI</button></div></section>
   </main><footer><Heart size={16}/> dibuat dengan banyak perasaan untuk {CONFIG.name} <Heart size={16}/></footer></>}

  <AnimatePresence>{letter!==null&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>{if(e.target===e.currentTarget)setLetter(null)}}><motion.div className="modal-paper" initial={{y:40,scale:.96}} animate={{y:0,scale:1}}><button className="close" onClick={()=>setLetter(null)} aria-label="Tutup"><X size={18}/></button><p className="eyebrow">LETTER 0{letter+1}</p><h2>{letters[letter][0]}</h2><img src={letters[letter][2]} alt="Surat"/><div className="scroll-letter"><p>{letters[letter][1]}</p><p className="signature">— {CONFIG.senderName} ♡</p></div></motion.div></motion.div>}</AnimatePresence>
  <AnimatePresence>{answer&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>{if(e.target===e.currentTarget)setAnswer(null)}}><motion.div className="answer-modal" initial={{y:30}} animate={{y:0}}><button className="close" onClick={()=>setAnswer(null)} aria-label="Tutup"><X size={18}/></button>{answer==='yes'&&<><div className="big-heart">💗</div><p className="eyebrow">MY FAVORITE ANSWER</p><h2>She said yes! ♡</h2><p>Serius? 🥹 Aku senang sekali. Terima kasih sudah membaca semuanya sampai di sini.</p><button className="primary" onClick={()=>whatsapp(`Aku sudah membaca semuanya... dan jawabanku: MAU ❤️`)}><Send size={16}/> Kirim jawaban ke aku</button></>}{answer==='no'&&<><div className="big-heart">🌸</div><p className="eyebrow">IT'S OKAY</p><h2>Aku mengerti. ♡</h2><p>Terima kasih sudah jujur dan sudah membaca semua yang aku tulis. Mungkin cerita kita belum sampai di bagian yang sama, dan itu tidak apa-apa. Aku tetap berharap hari ulang tahunmu indah.</p><button className="soft" onClick={()=>setAnswer(null)}>Kembali ke website ♡</button></>}{answer==='custom'&&<><div className="big-heart">💌</div><p className="eyebrow">YOUR HEART, YOUR ANSWER</p><h2>Jawab sesuai hatimu.</h2><p>Aku tidak ingin memaksamu memilih. Tulis saja apa yang sebenarnya ingin kamu katakan.</p><textarea autoFocus value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Tulis jawabanmu di sini..."/><div className="custom-actions"><button className="outline" onClick={()=>setAnswer(null)}>Kembali</button><button className="primary" disabled={!custom.trim()} onClick={()=>whatsapp(`Aku sudah membaca semuanya. Jawabanku: ${custom}`)}><Send size={16}/> Kirim jawabanku</button></div></>}</motion.div></motion.div>}</AnimatePresence>
  <AnimatePresence>{surprise&&<motion.div className="surprise-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true"><div className="surprise-particles">{Array.from({length:46},(_,i)=><span key={i} style={{'--i':i}}>✦</span>)}</div><div className="surprise-stage"><button className="surprise-close" onClick={()=>setSurprise(false)} aria-label="Tutup"><X/></button><div className="surprise-title">{'SELAMAT ULANG TAHUN SAVIRA'.split('').map((c,i)=><span key={i} style={{animationDelay:`${i*.075}s`}}>{c===' '?'\u00a0':c}</span>)}</div><div className="gift-scene"><div className="bucket">💐</div><div className="flower-pop f1">🌸</div><div className="flower-pop f2">🌷</div><div className="flower-pop f3">🌹</div><div className="flower-pop f4">🌺</div><div className="love-pop l1">💗</div><div className="love-pop l2">💖</div><div className="love-pop l3">💕</div><div className="teddy">🧸</div><div className="sparkle-pop">✨</div></div><p className="surprise-note">Semoga hari ini dipenuhi bunga, cinta, senyum, dan semua hal baik yang kamu pantas dapatkan. ♡</p><button className="primary" onClick={()=>setSurprise(false)}>Kembali ke website</button></div></motion.div>}</AnimatePresence>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
