import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence} from 'framer-motion';
import {Heart,Music2,Volume2,VolumeX,ChevronDown,Gift,Mail,Flower2,Sparkles,Send, LockKeyhole} from 'lucide-react';
import './style.css';

const CONFIG={
 name:'Savira', senderName:'Aku', pin:'021128', birthdayDate:'02 November',
 whatsapp:'628123456789', music:'/music/our-song.mp3',
 photos:{cover:'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&q=85',letter1:'https://images.unsplash.com/photo-1520857014576-2c4f4c972b57?auto=format&fit=crop&w=1200&q=85',letter2:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',letter3:'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1200&q=85',letter4:'https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=1200&q=85',special:'https://images.unsplash.com/photo-1494774157365-9e04c6720e47?auto=format&fit=crop&w=1200&q=85'},
 gifs:{birthday:'https://media.giphy.com/media/g9582DNuQppxC/giphy.gif',love:'https://media.giphy.com/media/26FLdmIp6wJr91JAI/giphy.gif',flower:'https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif'}
};
const letters=[
 ['Tentang Kamu','Ada banyak hal kecil tentang kamu yang entah kenapa selalu berhasil tinggal lebih lama di pikiranku. Senyummu, caramu bercerita, bahkan hal-hal sederhana yang mungkin tidak kamu sadari. Aku suka mengenalmu pelan-pelan, tanpa perlu memaksa cerita menjadi apa pun.',CONFIG.photos.letter1],
 ['Hal-Hal Kecil Yang Aku Suka','Aku suka ketika kamu menjadi dirimu sendiri. Cara kamu tertawa, cara kamu merespons sesuatu, dan perhatian kecil yang mungkin menurutmu biasa saja. Buatku, hal-hal sederhana itu justru yang paling mudah diingat.',CONFIG.photos.letter2],
 ['Yang Ingin Aku Katakan','Mungkin aku tidak selalu pandai mengatakan apa yang sebenarnya kurasakan. Tapi kalau ada satu hal yang ingin kamu tahu, kamu adalah seseorang yang berarti. Aku senang pernah punya kesempatan untuk mengenalmu lebih dekat.',CONFIG.photos.letter3],
 ['Satu Surat Paling Spesial','Hari ulang tahunmu membuatku punya alasan untuk menulis semua ini. Aku tidak tahu cerita kita akan berjalan ke mana, tapi aku ingin hari ini menyisakan satu kenangan kecil yang hangat untukmu. Semoga kamu selalu dikelilingi hal-hal baik.',CONFIG.photos.letter4]
];
function App(){
 const [stage,setStage]=useState('intro'),[pin,setPin]=useState(''),[music,setMusic]=useState(false),[letter,setLetter]=useState(null),[answer,setAnswer]=useState(null),[custom,setCustom]=useState('');
 const audio=useRef(null);
 useEffect(()=>{audio.current=new Audio(CONFIG.music);audio.current.loop=true;audio.current.volume=.38;return()=>audio.current?.pause()},[]);
 const startMusic=()=>{audio.current?.play().then(()=>setMusic(true)).catch(()=>{});};
 const enter=()=>{if(pin===CONFIG.pin){startMusic();setStage('loading');setTimeout(()=>setStage('envelope'),6500)}};
 const whatsapp=(msg)=>{window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank')};
 const scrollTo=(id)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 const particles=useMemo(()=>Array.from({length:34},(_,i)=>i),[]);
 return <div className="app">
  <div className="ambient"/>{particles.map(i=><span className="petal" key={i} style={{'--i':i}}/>)}
  <AnimatePresence mode="wait">
   {stage==='intro'&&<motion.section className="center-screen intro" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="moon">♡</div><p className="eyebrow">A LITTLE WORLD MADE FOR YOU</p><h1>Tonight, this little world<br/><em>belongs to you.</em></h1><p className="muted">Ada sesuatu yang aku siapkan khusus untukmu...</p><button className="primary" onClick={()=>setStage('pin')}>Enter <Heart size={16}/></button></motion.section>}
   {stage==='pin'&&<motion.section className="center-screen" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} exit={{opacity:0}}><div className="icon-orb"><LockKeyhole/></div><p className="eyebrow">A LITTLE SECRET</p><h2>Masukkan tanggal yang mungkin sudah kamu tahu.</h2><div className="pinbox">{[0,1,2,3,4,5].map(i=><span key={i} className={pin[i]?'filled':''}>{pin[i]||'•'}</span>)}</div><input autoFocus className="pin-input" type="tel" inputMode="numeric" pattern="[0-9]*" maxLength="6" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} onKeyDown={e=>e.key==='Enter'&&enter()} placeholder="Ketik 6 digit PIN" aria-label="Masukkan PIN 6 digit" /><button className="primary" onClick={enter}>Buka hadiah <Sparkles size={16}/></button>{pin&&pin!==CONFIG.pin&&pin.length===6&&<p className="error">Hmm... sepertinya belum tepat 🤭 Coba sekali lagi.</p>}</motion.section>}
   {stage==='loading'&&<motion.section className="cinematic" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="flower-scene"><div className="flower flower-a">🌸</div><div className="flower flower-b">🌷</div><div className="ring">💍</div><div className="sparkle s1">✦</div><div className="sparkle s2">✧</div></div><p className="eyebrow">A LITTLE SURPRISE FOR YOU...</p><h1>Selamat Ulang Tahun</h1><h2>{CONFIG.name} <span>♡</span></h2><p>Semoga hari ini menjadi salah satu hari paling indah untukmu...</p><button className="ghost" onClick={()=>setStage('envelope')}>Skip ♡</button></motion.section>}
   {stage==='envelope'&&<motion.section className="center-screen" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0}}><div className="envelope-wrap" onClick={()=>setStage('main')}><div className="envelope"><div className="seal">♡</div><div className="flap"/><div className="letter-peek">For Someone Special</div></div></div><p className="eyebrow">A LETTER FOR YOU</p><h2>There is something I want you to read...</h2><button className="primary" onClick={()=>setStage('main')}>Open Me <Mail size={17}/></button></motion.section>}
  </AnimatePresence>
  {stage==='main'&&<>
   <header className="nav"><div className="brand">♡ {CONFIG.name}</div><nav><button onClick={()=>scrollTo('letters')}>Letters</button><button onClick={()=>scrollTo('memories')}>Memories</button><button onClick={()=>scrollTo('birthday')}>Birthday</button></nav><button className="music" onClick={()=>{if(music){audio.current.pause();setMusic(false)}else{startMusic()}}}>{music?<Volume2 size={16}/>:<VolumeX size={16}/>} <Music2 size={15}/></button></header>
   <main>
    <section className="hero section"><div className="hero-copy"><p className="eyebrow">02 NOVEMBER · A DAY FOR YOU</p><h1>Untuk <em>{CONFIG.name}</em>,<br/>yang selalu punya<br/>cara sendiri untuk<br/><span>membuat hari terasa indah.</span></h1><p className="lead">Hari ini bukan cuma tentang bertambahnya usia. Ini tentang merayakan seseorang yang keberadaannya berarti.</p><button className="primary" onClick={()=>scrollTo('letters')}>Buka semua surat <ChevronDown size={17}/></button></div><div className="hero-photo"><img src={CONFIG.photos.cover}/><div className="photo-note">a little memory ♡</div></div></section>
    <section className="section intro-letter"><div className="paper"><p className="eyebrow">SURAT UTAMA</p><h2>Untuk kamu...</h2><img src={CONFIG.photos.cover}/><p>Kalau kamu sampai di halaman ini, berarti kamu sudah membuka sesuatu yang memang aku buat untukmu. Aku tidak ingin membuat hadiah yang hanya selesai ketika dibuka. Aku ingin setiap bagian kecilnya menyimpan satu pesan: bahwa hari ini kamu layak dirayakan.</p><p>Aku berharap kamu membaca semuanya dengan senyum. Tidak perlu terburu-buru. Anggap saja ini seperti aku duduk di dekatmu dan menceritakan hal-hal yang selama ini mungkin sulit aku ucapkan.</p><p className="signature">— {CONFIG.senderName} ♡</p></div></section>
    <section id="letters" className="section"><div className="section-head"><p className="eyebrow">LOVE LETTER COLLECTION</p><h2>Empat surat, empat cerita kecil.</h2></div><div className="letter-grid">{letters.map((l,i)=><motion.button whileHover={{y:-8,rotate:i%2?1:-1}} className="letter-card" key={l[0]} onClick={()=>setLetter(i)}><div className="mini-envelope"><span>♡</span></div><small>LETTER 0{i+1}</small><h3>{l[0]}</h3><p>Klik untuk membuka surat...</p></motion.button>)}</div></section>
    <section id="memories" className="section memories"><div className="section-head"><p className="eyebrow">LITTLE MOMENTS</p><h2>Beberapa hal yang ingin disimpan.</h2></div><div className="polaroids"><figure className="polaroid p1"><img src={CONFIG.photos.letter1}/><figcaption>A moment I don't want to forget.</figcaption></figure><figure className="polaroid p2"><img src={CONFIG.photos.letter2}/><figcaption>Your smile, quietly unforgettable.</figcaption></figure><figure className="polaroid p3"><img src={CONFIG.photos.letter3}/><figcaption>One little memory ♡</figcaption></figure></div></section>
    <section className="section garden"><div className="garden-copy"><p className="eyebrow">FLOWERS FOR YOU</p><h2>Kalau setiap bunga punya pesan...</h2><p>biarkan mereka menyampaikannya satu per satu.</p></div><div className="flowers"><span>🌹</span><span>🌷</span><span>🌸</span><span>💐</span><span>🌺</span></div></section>
    <section className="section reasons"><p className="eyebrow">IF YOU EVER ASK WHY</p><h2>Hal-hal kecil yang aku suka tentang kamu.</h2><div className="reason-list">{['Senyummu yang datang tanpa banyak usaha.','Cara kamu menjadi dirimu sendiri.','Hal-hal kecil yang mungkin kamu anggap biasa.','Caramu membuat hari yang biasa terasa sedikit berbeda.','Karena kamu adalah kamu.'].map((x,i)=><div className="reason" key={x}><b>0{i+1}</b><span>{x}</span><Heart size={18}/></div>)}</div></section>
    <section id="birthday" className="section birthday"><div className="cake">🎂</div><p className="eyebrow">TODAY IS YOUR DAY</p><h1>Happy Birthday,<br/><em>{CONFIG.name} ♡</em></h1><p>Semoga umur yang baru membawa lebih banyak alasan untuk tersenyum, lebih banyak hal baik untuk dikenang, dan lebih banyak mimpi yang berhasil kamu capai.</p><div className="wish">“Semoga kamu selalu menemukan cahaya bahkan di hari yang paling sederhana.”</div></section>
    <section className="section special"><div className="special-card"><img src={CONFIG.photos.special}/><div><p className="eyebrow">A SPECIAL MESSAGE</p><h2>Ada satu hal yang ingin aku titipkan.</h2><p>Aku tidak tahu apakah semua kata di sini bisa menjelaskan apa yang sebenarnya ingin aku sampaikan. Tapi setidaknya, semoga kamu tahu bahwa membuat hadiah ini adalah caraku mengatakan: kamu spesial.</p><p>Dan apa pun yang terjadi setelah halaman terakhir nanti, aku tetap berharap ulang tahunmu dipenuhi kebahagiaan.</p></div></div></section>
    <section className="section final-letter"><div className="paper dark-paper"><div className="heartbeat">♡</div><p className="eyebrow">ONE LAST LETTER</p><h2>Kalau kamu mau membaca satu hal sampai selesai...</h2><p>Aku ingin kamu tahu bahwa aku tidak membuat semua ini untuk memaksamu menjawab apa pun. Aku membuatnya karena ada seseorang yang ingin aku rayakan hari ini—kamu.</p><p>Mungkin aku terlalu banyak berharap, mungkin juga tidak. Tapi aku ingin jujur tentang satu hal: aku menyukaimu. Dan kalau ternyata perasaan ini punya tempat di hatimu juga, mungkin kita bisa mulai menulis cerita yang baru.</p><p className="signature">Selamat ulang tahun, {CONFIG.name}. ♡</p></div></section>
    <section className="section question"><p className="eyebrow">ONE LAST QUESTION</p><h1>{CONFIG.name}...</h1><p className="question-lead">Setelah semua surat kecil ini,<br/>aku ingin bertanya sesuatu.</p><h2>Mau nggak jadi pacar aku? <span>♡</span></h2><div className="answer-buttons"><button className="primary" onClick={()=>setAnswer('yes')}>💗 MAU</button><button className="soft" onClick={()=>setAnswer('no')}>🌸 GAK DULU</button><button className="outline" onClick={()=>setAnswer('custom')}>💌 JAWAB SESUAI HATI</button></div></section>
   </main>
   <footer><Heart size={16}/> dibuat dengan banyak perasaan untuk {CONFIG.name} <Heart size={16}/></footer>
  </>}
  <AnimatePresence>{letter!==null&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="modal-paper" initial={{y:40,scale:.96}} animate={{y:0,scale:1}}><button className="close" onClick={()=>setLetter(null)}>×</button><p className="eyebrow">LETTER 0{letter+1}</p><h2>{letters[letter][0]}</h2><img src={letters[letter][2]}/><p>{letters[letter][1]}</p><p className="signature">— {CONFIG.senderName} ♡</p></motion.div></motion.div>}</AnimatePresence>
  <AnimatePresence>{answer&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="answer-modal" initial={{y:30}} animate={{y:0}}>{answer==='yes'&&<><div className="big-heart">💗</div><p className="eyebrow">MY FAVORITE ANSWER</p><h2>She said yes! ♡</h2><p>Serius? 🥹 Aku senang sekali. Terima kasih sudah membaca semuanya sampai di sini.</p><button className="primary" onClick={()=>whatsapp(`Aku sudah membaca semuanya... dan jawabanku: MAU ❤️`)}><Send size={16}/> Kirim jawaban ke aku</button></>}{answer==='no'&&<><div className="big-heart">🌸</div><p className="eyebrow">IT'S OKAY</p><h2>Aku mengerti. ♡</h2><p>Terima kasih sudah jujur dan sudah membaca semua yang aku tulis. Mungkin cerita kita belum sampai di bagian yang sama, dan itu tidak apa-apa. Aku tetap berharap hari ulang tahunmu indah.</p><button className="soft" onClick={()=>setAnswer(null)}>Aku mengerti ♡</button></>}{answer==='custom'&&<><div className="big-heart">💌</div><p className="eyebrow">YOUR HEART, YOUR ANSWER</p><h2>Jawab sesuai hatimu.</h2><p>Aku tidak ingin memaksamu memilih. Tulis saja apa yang sebenarnya ingin kamu katakan.</p><textarea value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Tulis jawabanmu di sini..."/><button className="primary" disabled={!custom.trim()} onClick={()=>whatsapp(`Aku sudah membaca semuanya. Jawabanku: ${custom}`)}><Send size={16}/> Kirim jawabanku</button></>}</motion.div></motion.div>}</AnimatePresence>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
